#!/bin/sh

# Install vim plugin manager
#if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
#  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
#      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#fi
#vim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa

# Install oh-my-fish
if [ ! -d $HOME/.local/share/omf ]; then
  curl -L http://get.oh-my.fish | fish
fi
fish -c "omf install"
